# Generated by Django 5.2.12 on 2026-04-04 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='başlangıç')),
                ('ends_at', models.DateTimeField(db_index=True, verbose_name='bitiş')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal'), ('no_show', 'Gelmedi')], db_index=True, default='pending', max_length=32, verbose_name='durum')),
                ('source', models.CharField(choices=[('customer_app', 'Müşteri uygulaması'), ('business_manual', 'İşletme (manuel)')], default='customer_app', max_length=32, verbose_name='kaynak')),
                ('customer_note', models.TextField(blank=True, verbose_name='müşteri notu')),
                ('internal_note', models.TextField(blank=True, verbose_name='işletme notu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.business', verbose_name='işletme')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_appointments', to=settings.AUTH_USER_MODEL, verbose_name='müşteri')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.service', verbose_name='hizmet')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='business.staff', verbose_name='personel')),
            ],
            options={
                'verbose_name': 'randevu',
                'verbose_name_plural': 'randevular',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['staff', 'starts_at'], name='appointment_staff_i_889911_idx'), models.Index(fields=['business', 'starts_at'], name='appointment_busines_60eff6_idx')],
            },
        ),
    ]
