# Generated by Django 5.2.12 on 2026-04-04 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='işletme adı')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='kısa ad (URL)')),
                ('category', models.CharField(choices=[('barber', 'Berber'), ('hair_salon', 'Kuaför'), ('beauty_center', 'Güzellik merkezi')], db_index=True, max_length=32, verbose_name='kategori')),
                ('description', models.TextField(blank=True, verbose_name='açıklama')),
                ('address_line', models.CharField(max_length=512, verbose_name='adres satırı')),
                ('city', models.CharField(db_index=True, max_length=128, verbose_name='il / şehir')),
                ('district', models.CharField(blank=True, max_length=128, verbose_name='ilçe')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='boylam')),
                ('working_hours', models.JSONField(default=dict, help_text='Haftalık şablon — documentation/DATA-MODEL.md §4', verbose_name='çalışma saatleri')),
                ('timezone', models.CharField(blank=True, default='Europe/Istanbul', max_length=64, verbose_name='saat dilimi')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='yayında')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_businesses', to=settings.AUTH_USER_MODEL, verbose_name='işletme yetkilisi')),
            ],
            options={
                'verbose_name': 'işletme',
                'verbose_name_plural': 'işletmeler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='hizmet adı')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='süre (dakika)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='fiyat')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktif')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='business.business', verbose_name='işletme')),
            ],
            options={
                'verbose_name': 'hizmet',
                'verbose_name_plural': 'hizmetler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='görünen ad')),
                ('working_hours', models.JSONField(blank=True, help_text='Boşsa işletme saatleri geçerlidir.', null=True, verbose_name='çalışma saatleri')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='aktif')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='business.business', verbose_name='işletme')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to=settings.AUTH_USER_MODEL, verbose_name='kullanıcı hesabı')),
            ],
            options={
                'verbose_name': 'personel',
                'verbose_name_plural': 'personel',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes_override', models.PositiveIntegerField(blank=True, help_text='Boşsa hizmetin varsayılan süresi kullanılır.', null=True, verbose_name='süre geçersiz kılma (dakika)')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='business.service', verbose_name='hizmet')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_services', to='business.staff', verbose_name='personel')),
            ],
            options={
                'verbose_name': 'personel–hizmet',
                'verbose_name_plural': 'personel–hizmetler',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='services',
            field=models.ManyToManyField(related_name='staff_links', through='business.StaffService', to='business.service', verbose_name='verebildiği hizmetler'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_service_name_per_business'),
        ),
        migrations.AddConstraint(
            model_name='staffservice',
            constraint=models.UniqueConstraint(fields=('staff', 'service'), name='unique_staff_service'),
        ),
    ]
