# Generated by Django 5.2.12 on 2026-04-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='working_hours_exceptions',
            field=models.JSONField(blank=True, default=list, help_text='Belirli tarihlerde izin veya farklı saat (YYYY-MM-DD). Haftalık şablonu geçersiz kılar.', null=True, verbose_name='çalışma saati istisnaları'),
        ),
    ]
